- pyfr/partitioners/base.py
This fixes string type conversion of con Numpy array. We can correctly partitions/re-partitions mesh and/or solution.
> Fix a bug in combining partition.

- pyfr/integrators/steppers.py
Add 3rd order accurate TVD Runge-Kutta integrator
> Add the TVD-RK3 integrator.

- doc/ext/tikz.py
- pyfr/backends/base/generator.py
- pyfr/backends/cuda/cublas.py
- pyfr/backends/cuda/generator.py
- pyfr/backends/opencl/clblas.py
- pyfr/backends/opencl/generator.py
- pyfr/backends/opencl/provider.py
- pyfr/backends/openmp/types.py
- pyfr/integrators/controllers.py
- pyfr/partitioners/__init__.py
- pyfr/partitioners/metis.py
- pyfr/partitioners/scotch.py
- pyfr/readers/base.py
- pyfr/readers/gmsh.py
- pyfr/scripts/mesh.py
- pyfr/scripts/postp.py
- pyfr/writers/paraview.py
Minor refactoring/cleanup of the code along with some fixes for Python 3.
> Cleanups and Python 3 fixes

- doc/ext/tikz.py
- doc/src/user_guide.rst
- pyfr/backends/base/generator.py
- pyfr/backends/cuda/cublas.py
- pyfr/backends/cuda/generator.py
- pyfr/backends/opencl/clblas.py
- pyfr/backends/opencl/generator.py
- pyfr/backends/opencl/provider.py
- pyfr/backends/openmp/types.py
- pyfr/integrators/controllers.py
- pyfr/partitioners/__init__.py
- pyfr/partitioners/metis.py
- pyfr/partitioners/scotch.py
- pyfr/readers/base.py
- pyfr/readers/gmsh.py
- pyfr/scripts/mesh.py
- pyfr/scripts/postp.py
- pyfr/writers/paraview.py
This request adds support for sampling points inside of the domain.
> Add Point Sampling

- doc/src/user_guide.rst
- examples/couette_flow_2d/couette_flow_2d.ini
- examples/euler_vortex_2d/euler_vortex_2d.ini
- pyfr/integrators/base.py
- pyfr/integrators/controllers.py
- pyfr/integrators/writers.py
- pyfr/mpiutil.py
- pyfr/plugins/__init__.py
- pyfr/plugins/base.py
- pyfr/plugins/fluidforce.py
- pyfr/plugins/nancheck.py
- pyfr/plugins/sampler.py
- pyfr/shapes.py
- pyfr/solvers/base/elements.py
- pyfr/solvers/base/system.py
- pyfr/solvers/baseadvec/elements.py
This adds support for integrating up pressures on boundaries.  The syntax is:
```
[soln-plugin-fluidforce-name]
nsteps = 50
file = forces.csv
```
where `name` is the name of the boundary to integrate over.  Jin Seok and I have done some light testing but more is needed before we can consider merging.
In addition this request also:
* improves source term validation;
* extends the plugin system in a variety of ways and changes the prefix to `soln-` from `solver-`;
* eliminates the misleading use of `freq` for plugins and filters in lieu of `nsteps`.
> Real time integration of pressure on boundaries

- doc/src/user_guide.rst
- pyfr/backends/base/makoutil.py
- pyfr/solvers/base/elements.py
- pyfr/solvers/baseadvec/inters.py
- pyfr/solvers/euler/inters.py
- pyfr/solvers/euler/kernels/bccflux.mako
- pyfr/solvers/euler/kernels/bcs/char-riem-inv.mako
- pyfr/solvers/euler/kernels/bcs/slp-adia-wall.mako
- pyfr/solvers/euler/kernels/bcs/sup-in-fa.mako
- pyfr/solvers/navstokes/inters.py
- pyfr/solvers/navstokes/kernels/bccflux.mako
- pyfr/solvers/navstokes/kernels/bcconu.mako
- pyfr/solvers/navstokes/kernels/bcs/ghost.mako
- pyfr/solvers/navstokes/kernels/bcs/no-slp-adia-wall.mako
- pyfr/solvers/navstokes/kernels/bcs/no-slp-isot-wall.mako
- pyfr/solvers/navstokes/kernels/bcs/slp-adia-wall.mako
- pyfr/solvers/navstokes/kernels/bcs/sub-in-frv.mako
- pyfr/solvers/navstokes/kernels/bcs/sub-in-ftpttang.mako
- pyfr/solvers/navstokes/kernels/bcs/sub-out-fp.mako
- pyfr/solvers/navstokes/kernels/bcs/sup-out-fn.mako
- pyfr/solvers/navstokes/system.py
This implements the framework for a spatially and temporally
varying boundary condition. As an extension to the implementation
the sub-in-frv, sup-in-fa are now capable of taking in equations
in terms of x, y, z and t. Also, for the ease of usage, the
constants defined in the constants section are also available
in the equations.
> Implementation of space and time dependent bc.

- pyfr/solvers/navstokes/inters.py
Some minor formatting changes to ensure all lines are wrapped correctly.
> Minor formatting

- pyfr/solvers/navstokes/elements.py
- pyfr/solvers/navstokes/kernels/avis.mako
This request fixes a bug in artificial viscosity when flux anti-aliasing turns on.
> Fix a bug in artificial viscosity when anti-aliasing turns on.

- pyfr/polys.py
> Change xrange to range for Pyr shape.

- pyfr/solvers/baseadvec/system.py
- pyfr/solvers/baseadvecdiff/system.py
It fixes a bug when we use space and time dependent bc for Euler solver.
> Fix a bug in space and time dependent bc.

- pyfr/solvers/baseadvec/inters.py
- pyfr/solvers/euler/inters.py
- pyfr/solvers/euler/kernels/bcs/char-riem-inv.mako
- pyfr/solvers/navstokes/inters.py
This implements the Riemann invariant boundary condition with parameters
which vary over space.
> Spatially varying Riemann boundary condition

- pyfr/solvers/navstokes/inters.py
- pyfr/solvers/navstokes/kernels/bcs/sub-out-fp.mako
This implements the spatial and temporal variation in the subsonic
outflow conditions.
> Implementation of space-time varying sub-out-fp

- pyfr/plugins/residual.py
It fixes a bug in residual plugin. The previous solutions are deep-copied.
>  Fix a bug in residual plugin.

- pyfr/shapes.py
This resolves an issue around filtering tensor product elements that could result in the filtering being more aggressive than necessary.
> Improve filtering for tensor product elements.

- doc/src/user_guide.rst
- pyfr/plugins/fluidforce.py
- pyfr/solvers/base/elements.py
It improves the fluid force plugin to compute viscous force, as well as pressure force. There is an option to compute pressure force only or pressure and viscous forces.
type = viscous | pressure
> Fluid force plugin to compute viscous force.

- doc/src/user_guide.rst
- examples/couette_flow_2d/couette_flow_2d.ini
- examples/euler_vortex_2d/euler_vortex_2d.ini
- pyfr/h5writer.py
- pyfr/integrators/__init__.py
- pyfr/integrators/base.py
- pyfr/integrators/controllers.py
- pyfr/nputil.py
- pyfr/plugins/__init__.py
- pyfr/plugins/solnwriter.py
The implementation of the solution writer as a plugin comes with the following changes:
- The integrator is now a merge of the stepper and controller alone and not of the writer,
- The hdf5 writer is shifted to the root directory,
- The plugins can now set a 'dt', the interval after which the integrator is guaranteed to stop,
- The t0 is renamed to 'tstart' in the solver-time-integrator section of the ini file and is accompanied by the 'tend', which determines when the solver stops.
> This implements the solution writer as a plugin.

- pyfr/integrators/base.py
- pyfr/plugins/solnwriter.py
This commit modifies the solution writer plugin to make sure
it does not rewrite the initial file if the solution is restarted.
> Prevents rewriting restart file.

- pyfr/mputil.py
- pyfr/polys.py
This commit modifies the way to compute the derivative of basis function via chain rule.
> Compute derivative of basis function via chain rule.

- pyfr/plugins/__init__.py
- pyfr/plugins/tavg.py
Note that 'stats' are different to those added by the soon to be depreciated time-averaging utility. We can discuss what is most appropriate going forwards (in the context of the proposed improvements to this time-averaging plugin).
I have tested with the 2D Euler Vortex. Should probably test further before accepting.
> Added a time-averaging plugin.

- pyfr/solvers/euler/kernels/rsolvers/roem.mako
It fixes a possible bug to compute function f in RoeM flux.
> Possible bug fix for RoeM.

- doc/src/user_guide.rst
- pyfr/integrators/controllers.py
- pyfr/plugins/__init__.py
- pyfr/plugins/base.py
- pyfr/plugins/dtstats.py
- pyfr/plugins/fluidforce.py
- pyfr/plugins/residual.py
- pyfr/plugins/sampler.py
- pyfr/scripts/main.py
- pyfr/solvers/base/elements.py
- pyfr/util.py
- pyfr/writers/vtk.py
This request:
- Adds a plugin for tracking accepted/rejected time steps.
- Cleans up how plugins generate CSV files.
- Requires a backend to be specified when running PyFR (CUDA is no longer the default).
- Contains various cleanups.
> Incremental Improvements

- pyfr/shapes.py
- pyfr/solvers/base/elements.py
I have implemented the free-stream metric, which satisfies the discrete metric identity.
> Implementation of free-stream metric.

- doc/src/user_guide.rst
I have updated the User Guide. All the docs appear to build correctly.
> Updated User Guide.

- pyfr/solvers/euler/inters.py
Add a missing ploc parameter in EulerBaseBCInters
> Fix a bug for space-time BC in Euler system.

- pyfr/readers/base.py
This commit can check if the pyramids have a non-parallelogram base or not.
>  Implement routine to check if pyramids have a non-parallelogram base. 

- doc/src/user_guide.rst
- pyfr/plugins/dtstats.py
- pyfr/plugins/fluidforce.py
- pyfr/plugins/sampler.py
- pyfr/solvers/base/inters.py
- pyfr/solvers/baseadvec/inters.py
- pyfr/solvers/euler/inters.py
- pyfr/solvers/navstokes/elements.py
- pyfr/solvers/navstokes/inters.py
- pyfr/solvers/navstokes/kernels/intconu.mako
- pyfr/solvers/navstokes/kernels/mpicflux.mako
These changes clean up various bits of the code and also improve the start-up time associated with the point sampling plugin by using scipy.spatial.cKDTree where available.
> Cleanups and Improved Point Sampling

- pyfr/inifile.py
same fix done for the file nputil.py
> Fixed another issue with gradient averaging

- doc/src/user_guide.rst
let me know if you would like to make any changes. The Ubuntu one will follow soon.
G.
> Added quick-start installation guide for macOS and Ubuntu

- doc/src/developer_guide.rst
- pyfr/backends/base/backend.py
- pyfr/backends/base/generator.py
- pyfr/backends/base/kernels.py
- pyfr/backends/base/packing.py
- pyfr/backends/base/types.py
- pyfr/plugins/base.py
- pyfr/rank_allocator.py
- pyfr/readers/base.py
- pyfr/solvers/base/elements.py
- pyfr/solvers/base/system.py
This never really caught any issues but came with a few annoying
quirks.
> Migrate away from the Python abc module.

- pyfr/plugins/tavg.py
- pyfr/plugins/writer.py
- pyfr/writers/native.py
- pyfr/writers/vtk.py
- setup.py
This PR adds support to the file writing plugin for writing some subset of the full volume to disk.
> Add support for partial solution writing

- AUTHORS
- pyfr/integrators/dual/phys/base.py
- pyfr/integrators/dual/pseudo/__init__.py
- pyfr/integrators/dual/pseudo/base.py
- pyfr/integrators/dual/pseudo/multip.py
- pyfr/integrators/dual/pseudo/pseudocontrollers.py
- pyfr/integrators/dual/pseudo/pseudosteppers.py
Fix the collection of statistics (number of RHS evaluations, number of psuedo-steps and number of p-multigrid cycles) for dual integrators.
> Fix the collection of statistics for dual integrators.

- pyfr/plugins/fluidforce.py
Bug fix in viscous force computation when using Sutherland's law.
> Bug fix in viscous force computation.

- doc/src/user_guide.rst
- pyfr/shapes.py
- pyfr/solvers/base/elements.py
- pyfr/solvers/baseadvec/elements.py
- pyfr/solvers/baseadvec/system.py
- pyfr/solvers/baseadvecdiff/elements.py
- pyfr/solvers/baseadvecdiff/system.py
This removes support for div-flux anti-aliasing which has not been found to be particularly useful in real-world applications.
> Remove support for div-flux anti-aliasing.

- AUTHORS
- pyfr/plugins/__init__.py
- pyfr/plugins/integrate.py
- pyfr/writers/native.py
This allows for the integration of functions over the domain to be calculated and output to a file. Some slightly strange behaviour is observed in some cases, for example, energy in the TGV case, although enstrophy is fine. It is unclear if this is consistent or inconsistent with the solution.
> added instaneous global integrator plugin

- pyfr/solvers/base/elements.py
- pyfr/solvers/base/system.py
- pyfr/solvers/baseadvec/elements.py
- pyfr/solvers/baseadvec/system.py
- pyfr/solvers/baseadvecdiff/elements.py
- pyfr/solvers/baseadvecdiff/system.py
This does not typically result in a meaningful improvement in performance, but does add quite a bit of complexity.
> Remove support for int/ext sides.

- pyfr/solvers/base/elements.py
This PR subtly changes how Jacobian determinants are computed to allow for future performance improvements inside of some of the pointwise kernels.
> Simplify how the Jacobian determinants are computed.

- pyfr/__main__.py
- pyfr/partitioners/base.py
- pyfr/readers/base.py
- pyfr/readers/gmsh.py
- pyfr/solvers/base/system.py
- pyfr/writers/native.py
The key change here is that nodepts is now a dense NumPy array as opposed to a dict.  This will be important for robustly resolving #198
>  Rework how linear elements are identified.

- pyfr/backends/cuda/compiler.py
@WillTrojak could you check this please? thanks!
> Bug fix cuda compiler.

- pyfr/integrators/dual/pseudo/pseudocontrollers.py
- pyfr/integrators/std/controllers.py
Added on validity checks on `min-fact`, 'max-fact`, and `pseudo-dt-max-mult`
> Added some error checks on PI config.

- pyfr/plugins/base.py
- pyfr/plugins/tavg.py
- pyfr/plugins/writer.py
- pyfr/writers/native.py
It is now possible for data sets to be specified at the time a file is being written as opposed to when the NativeWriter is constructed.
> Make the file writing code more flexible.

- doc/src/user_guide.rst
- pyfr/plugins/sampler.py
- pyfr/polys.py
The plugin now makes use of Newton's method to invert the mapping function, enabling precise sampling (compared with the current approach of simply selecting the closest solution point).
> Enhance the point sampler plugin.

- pyfr/__main__.py
- pyfr/writers/base.py
- pyfr/writers/vtk.py
This removes the gradient export code and adds support for tagging the partition number of elements.
> Improve the VTK writer.

- doc/src/installation.rst
- pyfr/backends/opencl/base.py
- pyfr/backends/opencl/kernels/base.mako
- pyfr/backends/opencl/kernels/reduction.mako
This takes advantage of some of the functionality in OpenCL 2 to remove some clutter.
> OpenCL cleanups.

- doc/src/user_guide.rst
- pyfr/plugins/base.py
- pyfr/plugins/integrate.py
- pyfr/regions.py
It is now possible to combine different geometric regions together using addition and subtraction.  This makes it possible to construct some interesting shapes.
There is also support for writing multiple layers of elements adjacent to a boundary.  This is accomplished by appending +*n* where *n* is an integer to the end of the boundary name.
> Add basic constructive solid geometry support to the region code.

- pyfr/partitioners/base.py
- pyfr/readers/base.py
- pyfr/readers/native.py
Also, ensure that periodic faces are never split across partition boundaries.
> Tag periodic connectivity in the mesh file.

- pyfr/integrators/std/controllers.py
New alpha is 0.58, new beta is 0.42
> Modified controller parameters

- pyfr/plugins/tavg.py
Gradient computation now done by all ranks
> Bug fixes for gradient calculation

- pyfr/ctypesutil.py
- pyfr/nputil.py
Sorry about the excessive commits, somehow by git repo ended up a bit tangled and the rebase is showing all commits.
> Adding configurable mode to library loads

- doc/src/cli.rst
- doc/src/index.rst
- pyfr/__main__.py
- pyfr/integrators/base.py
- pyfr/integrators/dual/phys/base.py
- pyfr/integrators/dual/pseudo/multip.py
- pyfr/integrators/dual/pseudo/pseudocontrollers.py
- pyfr/integrators/std/base.py
- pyfr/plugins/__init__.py
- pyfr/plugins/ascent.py
- pyfr/plugins/base.py
- pyfr/plugins/dtstats.py
- pyfr/plugins/fluidforce.py
- pyfr/plugins/integrate.py
- pyfr/plugins/nancheck.py
- pyfr/plugins/pseudostats.py
- pyfr/plugins/residual.py
- pyfr/plugins/sampler.py
- pyfr/plugins/tavg.py
- pyfr/plugins/writer.py
- pyfr/solvers/base/system.py
- pyfr/solvers/baseadvec/elements.py
- pyfr/solvers/baseadvec/kernels/negdivconf.mako
Added p-multigrid support
[WIP] Added new plugin sub classes
[WIP] Plugin refactoring
> Refactored plugins, adding solver plugins

- pyfr/integrators/base.py
Fixes bug in plugins that occured when restarting a simulation.
> Fixed prefix alias bug

- doc/src/user_guide.rst
- pyfr/solvers/baseadvec/kernels/transform.mako
- pyfr/solvers/euler/inters.py
- pyfr/solvers/euler/kernels/flux.mako
- pyfr/solvers/euler/kernels/rsolvers/exact.mako
- pyfr/solvers/euler/kernels/rsolvers/hllc.mako
- pyfr/solvers/euler/kernels/rsolvers/roe.mako
- pyfr/solvers/euler/kernels/rsolvers/rsolve1d.mako
Added the exact riemann solver to the Euler solver. This also adds the option for riemann solves to be performed in the 1D transformed reference space, which can also simplify the methods for complex Riemann solvers like HLLC and Roe.
> Added exact Riemann solver for Euler

- pyfr/plugins/ascent.py
- pyfr/plugins/base.py
- pyfr/regions.py
@WillTrojak Let me know if this works for your FWH plugin.  It is now much easier to get the region object.
> Region cleanups.

- doc/src/user_guide.rst
- pyfr/plugins/base.py
- pyfr/plugins/fluidforce.py
- pyfr/solvers/base/elements.py
This allows new point sets to be generated for plugins, including surface quadratures.
> Added element mixin for surface quadrature

- pyfr/backends/cuda/packing.py
- pyfr/backends/hip/packing.py
Fix numpy import error to allow use of np.uintp
> fix numpy import error

- doc/src/user_guide.rst
- pyfr/plugins/__init__.py
- pyfr/plugins/base.py
- pyfr/plugins/fwh.py
- pyfr/regions.py
- pyfr/solvers/aceuler/elements.py
- pyfr/solvers/euler/elements.py
This is a spatial domain FWH solver, which greatly reduces the overhead and doesn't require special handling of restarts compared to frequency domain FWH.
> Adding FWH plugin

- pyfr/nputil.py
- pyfr/shapes.py
- pyfr/solvers/acnavstokes/inters.py
- pyfr/solvers/base/elements.py
- pyfr/solvers/baseadvecdiff/elements.py
- pyfr/solvers/baseadvecdiff/inters.py
- pyfr/solvers/baseadvecdiff/system.py
- pyfr/solvers/navstokes/inters.py
When flux points are a subset of solution points, this performs from additional optimisations. Currently, on p6 tets this gives about a 10% reduction in runtime.
> Lobatto point optimisation

- pyfr/solvers/euler/kernels/entropyfilter.mako
Forgot to add the order changes to the full filter operation.
> Update EF order for full filter.

- pyfr/polys.py
- pyfr/solvers/baseadvec/elements.py
- pyfr/solvers/baseadvec/system.py
- pyfr/solvers/euler/elements.py
- pyfr/solvers/euler/kernels/entropyfilter.mako
- pyfr/solvers/euler/kernels/entropylocal.mako
This PR extends EF to open solution node sets (e.g., Gauss-Legendre nodes) by evaluating the bounds and filter at the fpts in addition to the upts.
> Add capability for entropy filtering with open solution points.

- pyfr/solvers/euler/kernels/entropyfilter.mako
I don't think this expansion is needed with bisection.
> Expansion not needed with bisection

- pyfr/points.py
- pyfr/regions.py
- pyfr/resamplers.py
- setup.py
The latest release of rtree contains a new vectorised API (which I developed).  Using it enables us to greatly improve the performance of the point sampler, STL exporter, and resampler.
> Adopt the new rtree 1.4.0 API.

- pyfr/solvers/euler/kernels/rsolvers/hll.mako
- pyfr/solvers/euler/kernels/rsolvers/hllc.mako
This PR re-implements the HLL and HLLC schemes and corrects the speed of sound.
> Rework HLL / HLLC scheme

- pyfr/backends/base/backend.py
- pyfr/backends/cuda/cublaslt.py
- pyfr/backends/cuda/gimmik.py
- pyfr/backends/hip/gimmik.py
- pyfr/backends/hip/rocblas.py
- pyfr/backends/metal/gimmik.py
- pyfr/backends/opencl/gimmik.py
- pyfr/plugins/base.py
This takes us down to a single auto-tuning factor which is used everywhere.
> Further improve auto-tuning.

- pyfr/solvers/base/system.py
It was related to the previous unused entmin
> Unused getter

- pyfr/template.py
Here and implementation using the preprocessor argument instead of manually calling filter on the src string.
> Using mako preprocessor for filter stack
