PyFR/PyFR

pyfr/readers/native.py, pyfr/scripts/main.py, pyfr/writers/paraview.py
This commit implements the parallel vtu file writer for visualization
with paraview. The writer is invoked whtn the output file to be written
has a .pvtu extension.
The commit also implements the feature where the size of an array can
be ascertained without actually loading the array, when the underlying
file format supports it, as in the case of the new file format based on
HDF5.
=> Implemented the parallel vtu file writer.

pyfr/solvers/base/elements.py, pyfr/solvers/base/inters.py, pyfr/solvers/navstokes/elements.py, pyfr/solvers/navstokes/inters.py, pyfr/solvers/navstokes/kernels/avis.mako, pyfr/solvers/navstokes/kernels/bccflux.mako, pyfr/solvers/navstokes/kernels/bcs/ghost.mako, pyfr/solvers/navstokes/kernels/bcs/slp-adia-wall.mako, pyfr/solvers/navstokes/kernels/entropy.mako, pyfr/solvers/navstokes/kernels/flux.mako, pyfr/solvers/navstokes/kernels/intcflux.mako, pyfr/solvers/navstokes/kernels/mpicflux.mako, pyfr/solvers/navstokes/kernels/tflux.mako, pyfr/solvers/navstokes/system.py
I have added Persson's artificial viscosity scheme (AIAA 2006-0112). It requires three tuning parameters, which is defined in [solver-avis] section.
amu0 : maximum amount of artificial viscosity ~ h/p
s0 : cut-off of the smooth indicator ~ 1/p^4
kappa : range of the smooth indicator ~ empirically large
To get a proper values of them, you need to some (or many) trial-and-errors. 
This scheme is only working for Navier-Stokes system. If you want to simulate inviscid shock wave  flow, you should impose viscosity (mu in [solver] section) as 0.0.
=> Added Persson's artificial viscosity (AIAA 2006-0112).

pyfr/plugins/__init__.py, pyfr/plugins/fluidforce.py, pyfr/plugins/nancheck.py, pyfr/plugins/residual.py, pyfr/plugins/sampler.py
This adds a plugin for computing the residual.  It can be invoked by
```
[soln-plugin-residual]
nsteps = 50
file = resid.csv
header = true
```
The request also changes the existing plugins to use `nacptsteps` as opposed to `nsteps` when deciding if to run or not.  This results in more consistent output when an error estimating RK scheme is used.
=> Add a residual plugin

pyfr/writers/paraview.py
Numpy 1.10.0 version changes the default casting for inplace operations to
‘same_kind’. This breaks the paraview writer. This commit fixes this.
=> Fixes export for numpy 1.10 version.

pyfr/plugins/tavg.py, pyfr/plugins/writer.py
This remedies the accumulated error in dt_out which is compared with
intg.tcurr (which does not accumulate error).
=> Fixes the plugin dt_out accumulated error.

pyfr/plugins/fluidforce.py, pyfr/plugins/sampler.py, pyfr/plugins/tavg.py, pyfr/scripts/main.py, pyfr/solvers/base/elements.py, pyfr/solvers/euler/elements.py, pyfr/writers/vtk.py
This adds support inside of the VTU writer for exporting discontinuous gradients of the primitive variables through the `-g` flag.  A variety of performance improvements around the consistent handling of number precisions are also included.
Feedback appreciated.
=> Gradient export in the VTU writer

pyfr/plugins/fluidforce.py, pyfr/shapes.py, pyfr/solvers/baseadvec/inters.py, pyfr/solvers/euler/inters.py, pyfr/solvers/euler/kernels/intcflux.mako, pyfr/solvers/navstokes/inters.py, pyfr/solvers/navstokes/kernels/intcflux.mako
This commit change the way to save normal vector.
Previous: |J|J^-T n_ref
Now: |J|J^-T n_ref dS_ref
The proposed one can be interpreted as the physical infinitesimal volume.
dV_phy = n_phy dS_phy = |J| dV_ref = |J|J^-T n_ref dS_ref.
Thus, magnl = magnr
=> Compute the common normal vector

pyfr/shapes.py
This commit prevent degrading accuracy when we use the previous free-stream preserving metric. The polynomial order of metric is always the same as the solution polynomial order.
=> Fix a possible bug in metric basis regarding accuracy.

doc/src/user_guide.rst, pyfr/backends/cuda/blasext.py, pyfr/backends/cuda/kernels/axnpby.mako, pyfr/backends/mic/blasext.py, pyfr/backends/mic/kernels/axnpby.mako, pyfr/backends/mic/kernels/errest.mako, pyfr/backends/opencl/blasext.py, pyfr/backends/opencl/kernels/axnpby.mako, pyfr/backends/openmp/blasext.py, pyfr/backends/openmp/kernels/axnpby.mako, pyfr/backends/openmp/kernels/errest.mako, pyfr/integrators/__init__.py, pyfr/integrators/base.py, pyfr/integrators/dual/__init__.py, pyfr/integrators/dual/base.py, pyfr/integrators/dual/controllers.py, pyfr/integrators/dual/pseudosteppers.py, pyfr/integrators/dual/steppers.py, pyfr/integrators/std/__init__.py, pyfr/integrators/std/base.py, pyfr/integrators/std/controllers.py, pyfr/integrators/std/steppers.py, pyfr/solvers/euler/elements.py, setup.py
This request adds support for dual time stepping, developed by myself and Niki.  Various implicit schemes are implemented within this formulation and the existing systems have been extended to support dual time stepping formalism.
Support for the use of an uniform error norm inside of the adaptive RK schemes is also included.  This may yield better results for large scale systems however it is likely that the `atol` and `rtol` values will need to be relaxed slightly when this norm is employed.
=> Implement support for dual time stepping

doc/src/user_guide.rst, pyfr/backends/openmp/base.py, pyfr/backends/openmp/cblas.py, pyfr/backends/openmp/compiler.py, pyfr/backends/openmp/kernels/par-xsmm.mako, pyfr/backends/openmp/provider.py, pyfr/backends/openmp/xsmm.py, pyfr/inifile.py, pyfr/plugins/base.py, pyfr/plugins/tavg.py, pyfr/plugins/writer.py, pyfr/util.py, setup.py
Kernel caching is enabled by default with the cache directory determined by the appdirs module.  The default location can be overridden by exporting
PYFR_OMP_CACHE_DIR=/path/to/cache/dir
and disabled entirely by exporting PYFR_DEBUG_OMP_DISABLE_CACHE to any value.  The cache itself can be made read-only by making the cache directory read only.
Please note that even with the cache enabled and populated PyFR still requires access to the C compiler in order to determine the version string.
Further, this commit also adds optional support for using libxsmm as a matrix multiplication provider for the C/OpenMP backend.
These changes to a long way to improving the status of PyFR on KNL.  There is still much to do around improving start up time and run-time performance, however.
=> Add support for kernel caching to the C/OpenMP backend.

pyfr/writers/vtk.py
This commit creates safer names for pyfr export, replacing non ascii
characters with an underscore.
=> Safe names for (P)VTU fields.

.gitignore, doc/src/user_guide.rst, pyfr/ctypesutil.py
- Further modified the way the C runtime library is loaded to be friendly to Python 3.3 and 3.4 users on Windows
- Updated progress bar display
- Instruct to use mpiexec for parallel runs, as mpirun is not available from some distributions (i.e. MS-MPI)
- using the recommended "Development Mode" from distutils works well, but creates an egg-info folder in the root dir. gitignore'd it.
=> Improvements for Windows Platforms

pyfr/solvers/navstokes/inters.py, pyfr/solvers/navstokes/kernels/bcs/no-slp-isot-wall.mako
No-slip isothermal BC did not allow expressions for x,y,z. Changed the function for evaluating the BC options to be more consistent with the other BCs (_eval_opts to _exp_opts) which allow expressions. Isothermal BC mako file syntax for loop through 'uvw' changed as well.
=> Updated no-slip isothermal BCs

pyfr/backends/base/__init__.py, pyfr/backends/base/backend.py, pyfr/backends/base/kernels.py, pyfr/backends/base/types.py, pyfr/backends/cuda/base.py, pyfr/backends/cuda/types.py, pyfr/backends/opencl/base.py, pyfr/backends/opencl/types.py, pyfr/backends/openmp/base.py, pyfr/backends/openmp/types.py, pyfr/partitioners/base.py, pyfr/solvers/aceuler/elements.py, pyfr/solvers/acnavstokes/elements.py, pyfr/solvers/base/elements.py, pyfr/solvers/base/system.py, pyfr/solvers/baseadvec/elements.py, pyfr/solvers/baseadvec/system.py, pyfr/solvers/baseadvecdiff/elements.py, pyfr/solvers/baseadvecdiff/system.py, pyfr/solvers/euler/elements.py, pyfr/solvers/navstokes/elements.py
This PR aims to improve the strong scaling of PyFR.  Specifically, it should improve performance in instances where network bandwidth is a limiting factor.  It accomplishes this by splitting elements into two groups: those whose who have faces which are on the exterior of a partition and everything else.  The elements in the first group are then subject to priority processing which enables us to start MPI send/recv operations sooner.  This allows more time for them to complete.
=> Improve strong scaling by enabling additional overlap

pyfr/__main__.py, pyfr/backends/openmp/blasext.py, pyfr/partitioners/base.py
This PR adds an optional argument to the partition command to have it write out a .csv file containing the mapping between old element partition indices to the new element partition indices.
=> Add support for writing out the partitioner remapping table.

pyfr/inifile.py
This could cause problems in systems with 11 or more field variables.
=> Fix a minor issue in the expression evaluation routine.

pyfr/plugins/tavg.py
This PR contains several changes to the time averaging plugin.  Specifically:
- It is possible to delay averaging until a specific simulation time with the `tstart` key.  This defaults to 0. 
- It introduces a new kind of average called a `fun-avg` which can reference other average terms (but not the solution).  These can be used to compute fluctuations and are evaluated when the average is being written out to disk.
- It adds a new `mode` key which dictates how the averaging process proceeds.  In `windowed` mode, which is the default, each output file contains just the average data for its `dt-out` time window.  In `continuous` mode each output file contains the average data from `tstart` until the current time.
=> Enhance the time averaging plugin.

pyfr/backends/cuda/base.py, pyfr/backends/cuda/blasext.py, pyfr/backends/cuda/compiler.py, pyfr/backends/cuda/cublas.py, pyfr/backends/cuda/driver.py, pyfr/backends/cuda/gimmik.py, pyfr/backends/cuda/packing.py, pyfr/backends/cuda/provider.py, pyfr/backends/cuda/types.py, setup.py
This simplifies building PyFR on clusters and also enables us to make use of NVRTC.
=> Remove the dependency on PyCUDA in lieu of our own wrappers.

pyfr/backends/base/generator.py, pyfr/backends/cuda/generator.py, pyfr/backends/cuda/provider.py, pyfr/backends/hip/generator.py, pyfr/backends/hip/provider.py, pyfr/backends/opencl/generator.py, pyfr/backends/opencl/provider.py, pyfr/backends/openmp/generator.py, pyfr/shapes.py, pyfr/solvers/aceuler/elements.py, pyfr/solvers/aceuler/kernels/tflux.mako, pyfr/solvers/aceuler/kernels/tfluxlin.mako, pyfr/solvers/acnavstokes/elements.py, pyfr/solvers/acnavstokes/kernels/tflux.mako, pyfr/solvers/acnavstokes/kernels/tfluxlin.mako, pyfr/solvers/base/elements.py, pyfr/solvers/base/system.py, pyfr/solvers/baseadvec/kernels/smats.mako, pyfr/solvers/baseadvec/system.py, pyfr/solvers/baseadvecdiff/elements.py, pyfr/solvers/baseadvecdiff/kernels/gradcoru.mako, pyfr/solvers/baseadvecdiff/kernels/gradcorulin.mako, pyfr/solvers/baseadvecdiff/system.py, pyfr/solvers/euler/elements.py, pyfr/solvers/euler/kernels/tflux.mako, pyfr/solvers/euler/kernels/tfluxlin.mako, pyfr/solvers/navstokes/elements.py, pyfr/solvers/navstokes/kernels/tflux.mako, pyfr/solvers/navstokes/kernels/tfluxlin.mako
This enables us to reduce the amount of memory bandwidth required
for a step by computing Jacobian entries on the fly from the vertex
data.
=>  Separate out linear elements from curved elements. 

pyfr/integrators/base.py, pyfr/integrators/dual/phys/base.py, pyfr/integrators/dual/phys/controllers.py, pyfr/integrators/std/base.py, pyfr/integrators/std/controllers.py, pyfr/plugins/integrate.py, pyfr/plugins/tavg.py, pyfr/solvers/acnavstokes/elements.py, pyfr/solvers/base/elements.py, pyfr/solvers/base/system.py, pyfr/solvers/baseadvecdiff/system.py, pyfr/solvers/navstokes/elements.py
Hi everyone,
It seems that when analyzing the pressure-dilatation terms  of the default TGV vortex [1] using the integrate plugin as
`int-dissipationPressure = p*(grad_u_x + grad_v_y + grad_w_z)`
, the results are very far from the expected ones (two-order of magnitudes higher), although other quantities such as kinetic energy dissipation are very close to those shown in the literature. I also observed these issues with my in-house code (which uses a similar approach to compute the gradients in the postprocessing stages). Therefore, I tried to fix the issue by relying on the corrected gradients of the velocity at solution points, instead of the gradients computed using the nodal solution basis. When using these corrected gradients, the results are much closer to those obtained in the …
=> integrate: use corrected velocity grads with Navier-Stokes

pyfr/solvers/baseadvecdiff/elements.py
The tplargs used by self.kernels['gradcoru_upts_curved']
and self.kernels['gradcoru_upts_linear'] was being overwritten
by the created for in self.kernels['shocksensor']
This regression issue didn't allow to run simulations with artificial viscosity
=> ShockSensor: fix tplargs

pyfr/backends/base/makoutil.py, pyfr/backends/base/types.py, pyfr/inifile.py, pyfr/polys.py, pyfr/quadrules/__init__.py, pyfr/readers/native.py
This PR migrates away from various deprecated interfaces which are going away in Python 3.9 and future NumPy releases.
=> Python 3.10 support

doc/src/user_guide.rst, pyfr/plugins/integrate.py, pyfr/solvers/base/elements.py
1) Allow to access `tcurr` using `t` within the expressions of the integrate plugin (useful to compute errors with respect to analytical solutions)
2) Allow to choose the quadrature degree used to evaluate the expressions in the plugin integrate. To do so, the token `quad-deg` needs to be added to the input file in the integrate plugin section. The default quadrature type is taken from that used to set the solution points. If the user adds `quad-pts-{etype} = quad_name` to the integrate plugin section, then the the `quad_name quadrature will be used`.
Example:
```
[soln-plugin-integrate]
nsteps = 10
quad-deg = 10 ; quadrature degree
quad-pts-tet = witherden-vincent ; quadrature type
file = integrate
int-rho = rho
```
=> Integrate plugin enhancements (quad-deg, quad-pts and access to tcurr)

pyfr/backends/openmp/kernels/reduction.mako
Current pseudo-residual calculation is bugged if there is padding. 'atol' is added to denominator fix this.
=> Fix a bug in reduction kernel.

pyfr/readers/base.py
Define an element as linear when max deltas in all directions (not just any of them) are less than the given tolerance.
=> Bug fix in linearisation of elements.

pyfr/solvers/acnavstokes/inters.py, pyfr/solvers/acnavstokes/kernels/bcs/no-slp-wall.mako
I think this feature was missed off, should now be in line with `no-slp-isot-wall` for the Navier-Stokes solver.
=> Added support for acm-ns no-slp-wall bc with expressions for u,v,w.

pyfr/backends/hip/blasext.py, pyfr/backends/hip/generator.py, pyfr/backends/hip/gimmik.py, pyfr/backends/hip/kernels/axnpby.mako, pyfr/backends/hip/kernels/pack.mako, pyfr/backends/hip/kernels/reduction.mako, pyfr/backends/hip/packing.py, pyfr/backends/hip/provider.py
This fixes a performance regression with recent versions of HIP.
=> Add support for __launch_bounds__ in the HIP backend.

pyfr/integrators/dual/phys/controllers.py, pyfr/integrators/std/controllers.py, pyfr/plugins/residual.py, pyfr/plugins/writer.py
This separates the initialisation from the first call so that all plugins are initialised before any of them is actually called. This will allow plugins to interact with each other, if necessary.
=> All plugins are called for the first time outside their init function

pyfr/partitioners/base.py, pyfr/partitioners/metis.py
Changes to account for the case when the mesh has very few elements (not any multiple of 64, min n subelements). In this case the mesh is not partitioned and there is an exception to handle the case of Metis returning wrong indecies for one partition.
=> fix a metis partitioner error when mesh has only one partition

doc/src/user_guide.rst, examples/inc_cylinder_2d/inc_cylinder_2d.ini, pyfr/integrators/base.py, pyfr/integrators/dual/phys/base.py, pyfr/integrators/dual/phys/controllers.py, pyfr/integrators/dual/phys/steppers.py, pyfr/integrators/dual/pseudo/__init__.py, pyfr/integrators/dual/pseudo/base.py, pyfr/integrators/dual/pseudo/multip.py, pyfr/integrators/dual/pseudo/pseudocontrollers.py, pyfr/integrators/dual/pseudo/pseudosteppers.py
This PR adds support to use any integration scheme that falls under DIRK as long as the Butcher tableau is provided. For now I added ESDIRK3 coefficients into phys/steppers.py, but we may want to change this and add coefficents into text files like Niki did for Brian's schemes.
I tested bdf and dirk steppers with the inc_cylinder example and it works all fine with multip and local-pi, but the implementation is not final yet. I just wanted to discuss the structure and I'm open to suggestions related to this integrator in general.
@FreddieWitherden @pv101 @GiorgioGiangaspero @WillTrojak @GonzaloSaez  
Remaining work
- Freddie wants to remove bdf2 and bdf3 schemes. Any objections? My plan is to remove bdf2/3 support with a different commit in this PR, so that we have both dirk and bdf stuff …
=> Add support for DIRK integrators.

doc/src/performance_tuning.rst, pyfr/__main__.py, pyfr/backends/cuda/types.py, pyfr/backends/hip/types.py, pyfr/util.py, setup.py
This makes use of the newer CUDA-array-interface for decorating buffers and also automatically sets the relevant UCX environment variables.  Although we are not yet able to automatically enable such functionality, we are getting closer.
=> Improve support for CUDA- and HIP-aware MPI.

pyfr/backends/base/backend.py, pyfr/backends/openmp/compiler.py, pyfr/backends/openmp/types.py, pyfr/polys.py, pyfr/readers/native.py, pyfr/shapes.py, pyfr/solvers/base/elements.py, pyfr/util.py
Since Python 3.8 equivalent functionality to our venerable @lazyprop is available through the standard library.
=> Replace @lazyprop with @functools.cached_property.

pyfr/integrators/dual/phys/base.py, pyfr/integrators/dual/phys/controllers.py, pyfr/integrators/dual/pseudo/multip.py, pyfr/integrators/dual/pseudo/pseudocontrollers.py, pyfr/integrators/std/base.py, pyfr/integrators/std/controllers.py, pyfr/solvers/base/system.py, pyfr/solvers/baseadvec/system.py, pyfr/solvers/baseadvecdiff/system.py, pyfr/util.py
This class was useful back when the backend queues made extensive use of `__call__`.  However, since then their utility has diminished and many uses are vestigial.  This PR replaces any remaining uses with explicit for loops, which are arguably more intuitive.
=> Eliminate the proxylist class.

doc/src/conf.py, doc/src/installation.rst, pyfr/backends/base/kernels.py, pyfr/backends/cuda/provider.py, pyfr/backends/hip/provider.py, pyfr/backends/opencl/base.py, pyfr/backends/opencl/blasext.py, pyfr/backends/opencl/clblast.py, pyfr/backends/opencl/driver.py, pyfr/backends/opencl/gimmik.py, pyfr/backends/opencl/packing.py, pyfr/backends/opencl/provider.py, pyfr/backends/opencl/types.py, pyfr/backends/openmp/provider.py, pyfr/ctypesutil.py, setup.py
This eliminates a dependency and also enables us to reduce API overhead by caching kernel arguments (something which is not possible with PyOpenCL).
=> Rewrite the OpenCL backend to use our own wrappers.

pyfr/backends/base/kernels.py, pyfr/backends/cuda/provider.py, pyfr/backends/hip/provider.py, pyfr/backends/opencl/provider.py, pyfr/backends/openmp/blasext.py, pyfr/backends/openmp/compiler.py, pyfr/backends/openmp/generator.py, pyfr/backends/openmp/gimmik.py, pyfr/backends/openmp/kernels/axnpby.mako, pyfr/backends/openmp/kernels/batch-gemm.mako, pyfr/backends/openmp/kernels/pack.mako, pyfr/backends/openmp/kernels/par-memcpy.mako, pyfr/backends/openmp/kernels/reduction.mako, pyfr/backends/openmp/packing.py, pyfr/backends/openmp/provider.py, pyfr/backends/openmp/xsmm.py
All kernels now accept a pointer to a structure.  This reduces overhead and will, in the feature, enable the OpenMP backend to support a task-graph interface.
=> Rework how arguments are passed to OpenMP kernels.

pyfr/backends/base/makoutil.py, pyfr/integrators/dual/pseudo/kernels/localerrest.mako
Pow is slow on many platforms, especially CPU architectures without vectorised math libraries.  This PR replaces the pow calls with polynomial approximations.  Some more thought is needed around the domain and degree of these polynomials.
=> Avoid calling pow in localerrest.

pyfr/solvers/aceuler/elements.py, pyfr/solvers/acnavstokes/elements.py, pyfr/solvers/baseadvec/elements.py, pyfr/solvers/baseadvecdiff/elements.py, pyfr/solvers/euler/elements.py, pyfr/solvers/navstokes/elements.py
This avoids some matrix multiplication operators where A = 0, which causes issues for libxsmm.  It also results in a very slight reduction in overhead, as we now run fewer kernels at p = 0.
=> Elide some kernels at p = 0.

pyfr/regions.py
This is old numpy syntax and casues pyfr to fail.
=> Removed old np.bool

doc/src/user_guide.rst, pyfr/plugins/integrate.py
Adds an option to the integrate plugin for setting a degree for lp norm allowing the integrate plugin to calculate lp norms.
This is particualrly useful when analysing methods where L1, L2 and Linf norms of error are widely used. Previously you could do L1, and dodge L2 doing the sqrt in post, but there was no way to do Linf.
If the option is not present then the native approach is used where the expressions are just integrated.
=> Added optional lp norm in integrate plugin.

doc/src/cli.rst, pyfr/inifile.py, pyfr/plugins/__init__.py, pyfr/plugins/base.py, pyfr/plugins/tavg.py, pyfr/readers/__init__.py, pyfr/util.py
Plugins can now expose functions to be called from the commadn line. This is to allow for existing plugin infrastucture to be used to perform addition analysis tasks in pre- and post-processing, rather than relying on adhoc tools.
A new cli section has been added to the documentation. Currently the exposed plugin functions are:
* tavg merge --- allowing multiple time average files to be merged. 
* writer export --- this moves the export funtionality from a major command to a subcommand of the writer.
=> Added command line interface to plugins

pyfr/solvers/euler/inters.py, pyfr/solvers/euler/kernels/rsolvers/exact.mako, pyfr/solvers/euler/kernels/rsolvers/hllc.mako, pyfr/solvers/navstokes/inters.py
Soe fixes for the recent 1D'd riemann solvers.
* Fixed issue of p_min not being set in euler BCS and Navier--Stokes interfaces
* Changed HLLC wave speed estimate back to Einfeldt from Davis as Davis caused double mach reflection to nan on single precision
* Some cleanups to the exact solver
=> Fixed issues with 1D Riemann solvers

pyfr/backends/cuda/driver.py, pyfr/backends/hip/driver.py
This ensures that we do not try and run with incompatible versions of CUDA or HIP.  The major version check for HIP is needed as the device properties structure is changing with v6.
=> Add explicit version checks to CUDA and HIP.

pyfr/plugins/ascent.py
This adds the saving of the things to the PNG metadata of images produced by Ascent. Currently, the config, mesh-uuid, and time are saved. There is potential for adding additional syntax to the config to allow user notes, but I'm open to ideas. 
This is reliant on https://github.com/Alpine-DAV/ascent/pull/1199/
=> Added metadata to ascent PNG

pyfr/plugins/turbulence.py
The 3rd term in Rot in plugins/turbulence.py currently outputs a scalar, which should output an outer product in the form of 3x3 matrix. This PR fixes the equation, and the simulation results are verified locally.
=> Fix the 3rd term in Rot to output 3x3 outer product matrix in plugins/turbulence.py 

AUTHORS, doc/src/user_guide.rst, pyfr/backends/hip/rocblas.py
The heuristics in the rocblas aren't great for some of the gemm kernels used by pyfr. This approach uses a beta function in the rocblas extensions that gets all feasible algorithms, benchmarks them, and returns the best one. For some sizes, the improvement can be quite large.
This has only been tested on rocm 5.7, as I don't have access to 6.0 yet.
=> Rocblas benchmarking and algo picker

pyfr/solvers/base/elements.py
Currently we're getting an error if we try to turn gradient fusion off while flux AA is off. This is due to the new buffer, `_grad_upts`, introduced with gradient fusion being used in most of the kernels in place of `_vect_upts`. `_grad_upts` used to point `_vect_upts` and all was fine but this was recently changed in #400 to be able to run Euler solver with flux AA on. 
Alternative fix to the current issue would be having a `_vect_upts` buffer in `baseadvec` all the time even when flux AA is on, and have `_grad_upts` point to `_vect_upts` all the time. But this would increase memory use unnecessarily for the Euler solver when flux AA is on.
Later on I want to look into using `_grad_upts` buffer only inside `tdisf_fused` so that we can bring back the ability to turn of gradient fusion …
=> Disable being able to turn gradient fusion off when flux AA is off

pyfr/backends/openmp/types.py, pyfr/solvers/base/system.py, pyfr/solvers/baseadvec/system.py, pyfr/solvers/baseadvecdiff/system.py
The ideal grouping for the Euler solver discussed in https://www.sciencedirect.com/science/article/pii/S0010465521003052 is
`tdisf + tdivptcorf + tdivtconf + negdivconf`,
however this requires moving communication kernels around.
To begin with I grouped
`tdisf + tdivptcorf` and `tdivtconf + negdivconf` separately.
Similarly, groupings for the Navier-Stokes equation described in https://arxiv.org/abs/2401.06132 require moving around some of the communication kernels. Thus, I implemented only
`tdivtconf + negdivconf`
which is a grouping in the final configuration article recommends. I'll implement the big chunk of kernels grouped together in the article as a next step.
Communication kernels arranged so that the communication and computation is overlapped as much as possible. Moving them …
=> Add kernel groupings for enabling cache blocking

pyfr/solvers/navstokes/kernels/bcs/sub-in-ftpttang.mako
Fixes a minor robustness issue for computing `sqrt(udotu)` in pressure/temperature BCs where zero velocity states (such as at startup) can cause roundoff issues due to `pt = p`.
=> Bug fix in pressure/temperature BCs.

pyfr/backends/base/makoutil.py
Checking for a missed comma in params list at macro definition.
If one omits a comma in the params lists, the current checks will not catch them, and the result is a reuse of variable names generated. 
This will catch white space in params list definition, and assert the lengths of a pyfr.expands' param list is equal to the length of a macros param list.
=> Increased checks in mako params/extern macro definitions.

pyfr/inifile.py
Modified inifile.py to include '#' as inline comment prefix:
```
def __init__(self, inistr=None):
self._cp = cp = ConfigParser(inline_comment_prefixes=[';', '#'])
```
=> Updated inifile.py to accept both ';' and '#' as inline comment prefix

doc/src/performance_tuning.rst, pyfr/integrators/base.py, pyfr/integrators/dual/phys/base.py, pyfr/integrators/std/base.py
This PR attempts to provide more detailed accounting of plugin runtime by breaking out time spent getting common quantities such as the solution.  Currently, this is accounted to the first plugin on a given time step to request such a quantity.
=> Improve plugin time accounting.

pyfr/integrators/std/base.py
preproc expects a bank not array as input.
This issue was causing the `preproc` method to miss relevant kernels with it's `_get_kernel` call as the input was an array, not a bank. 
The result was most of the preprocessing kernels were not committed and a proper flow field was not being generated when the preprocessor was called, i.e. first calls of boundary conditions, boundary entropy filtering, were being computed with all zero `uin` array on the very first call. It was then corrected with the first pass of the rhs graph.
Test cases appear visually identical after change.
=> preproc expects a bank not array as inupt

pyfr/solvers/baseadvec/inters.py, pyfr/solvers/baseadvec/system.py, pyfr/solvers/euler/inters.py, pyfr/solvers/navstokes/inters.py
Now that the preproc graphs are running properly, there seems to be a bug with running p0 with entropy filtering enabled (even though it shouldn't do anything) due to the disu kernel not being called in preproc: `KeyError: <pyfr.backends.cuda.gimmik.CUDAGiMMiKKernels.mul.<locals>.MulKernel object at 0x0000020A8999E230>`
=> Minor bugfix in preproc graph.

doc/src/systems/solver-entropy-filter.rst, pyfr/solvers/baseadvec/elements.py, pyfr/solvers/euler/elements.py, pyfr/solvers/euler/kernels/entropyfilter.mako
This PR adds the option to use the linearized formulation for the entropy filter from Ching et al. (10.1016/j.jcp.2024.112881), which linearizes the pressure/entropy constraints and uses a linear Zhang/Shu-type limiter. This avoids the root-finding problem for EF at the expense of a more dissipative limiter (which can also sometimes be beneficial for strong shocks/poor grids).
=> Add linearized constraint/filter kernel for EF.

pyfr/plugins/ascent.py
Ascent throws an error when trying to write metadata to PNGs when running on Alps. I've raised an issue which has more detail on this here: https://github.com/Alpine-DAV/ascent/issues/1389 
It boils down to an issue that is occurring when it tries to convert a float (the simulation time in this case) to a string. Doing this conversion in PyFR is a workaround that prevents the error - I don't know if we want to include this fix now or wait and see what the Ascent developers say.
=> Workaround for Ascent bug when running on Alps

pyfr/backends/openmp/provider.py, pyfr/backends/openmp/types.py, pyfr/solvers/base/system.py, pyfr/solvers/baseadvec/system.py, pyfr/solvers/baseadvecdiff/system.py
The kernel groupings in Euler solver in PyFR v2.0.0 were chosen so that it wouldn't impact the performance in any other backend. There is a better kernel grouping possibility, but it may have an impact on scalability on all backends. This is because the best kernel grouping involves kernels from `g1` and `g2`. Thus, enabling the best kernel grouping requires moving some kernels from `g1` into `g2`, and this reduces the computation-communication overlap, potentially making the performance at scale worse for all backends.
@sambitmishra98, can you please test the scalability with the changes in this PR on the CUDA backend when you have time? I think comparison between the current develop branch and this PR up to 16 GPUs would be great. Please start with a mesh large enough to fill %80 of the …
=> Improve the kernel groupings in Euler and Navier-Stokes solvers.

pyfr/solvers/baseadvecdiff/system.py
Added a dependency to the artvisc_fpts_send MPI request to make sure it begins after the packing kernel has finished executing.
=> Fixes potential dependency issue with artvisc

pyfr/backends/base/types.py
This PR fixes mismatch in exchange matrix shapes between backends using blocked matrices (currently only OpenMP backend) and non-blocked matrices (currently, all other backends).
=> Ensure non-blocked exchange matrices across all backends

pyfr/solvers/baseadvec/elements.py
I don't think it is necessary to set this to none and is causing incorrect behavior downstream when entropy filtering is not being used and checks using `hasattr` are made, see: https://github.com/PyFR/PyFR/blob/52b34313755cc4160b686057229804c880339d36/pyfr/solvers/base/system.py#L65
I cannot find any logic where entorpy filtering is not being used, but the `entmin_int` variable is required to be `None`.
=> Variable not necessary

pyfr/backends/openmp/types.py
This pull request inserts a cache blocking group into a graph's run order while respecting dependencies. Previously, a group replaced its last running kernel in a graph's run order without checking for dependencies. Now, the position of each kernel within a group is considered, with the earliest position that doesn't violate any dependencies being selected.
I've also added a quick sanity check afterwards to check that this positioning does not violate other dependencies.
=> Respecting dependencies when inserting a cache blocking group into the run order for the OpenMP backend

pyfr/solvers/navstokes/inters.py, pyfr/solvers/navstokes/kernels/bcs/ghost-imperm.mako, pyfr/solvers/navstokes/kernels/bcs/no-slp-adia-wall.mako
This PR addresses viscous wall boundary conditions and their impermeability.
**Adiabatic No Slip Walls - Temperature Gradient**
The viscous flux is adiabatic when the normal flux calculation for the energy equation is zero. For heat conduction, this is achieved by setting the normal temperature gradient to be zero (shear stress energy is zero from zero velocity at the wall). Currently:
1. `ldg-state` (prescribing `ur` from `ul`) sensibly sets the wall solution momentum to zero, and matches density and internal energy from the fluid side. 
2. `ldg-grad-state` (prescribing `gradur` from `gradul`,`ul`) we copy all gradients from the left to the right, and then modify the total energy gradient s.t. when computing the temperature gradient in the viscous flux calculation, the normal temperature …
=> Add impermeable ghost state calculation for viscous walls

pyfr/integrators/base.py, pyfr/integrators/dual/phys/base.py, pyfr/plugins/tavg.py, pyfr/plugins/writer.py
This PR is in relation to this forum post: https://pyfr.discourse.group/t/tavg-merge-and-tavg-plugin-using-adaptive-time-step/1229/5
There are 2 parts to this PR, the first part is setting `tout_last` in the tavg plugin when restarting so that the output files are written at the expected times. For example, when restarting from t=0.01 and setting dt-out=0.01 you would expect the next tavg file to be written at 0.02 but it was instead being output at 0.02 + dt. This PR fixes it (tested on the example in the forum post).
The second part is writing tavg files at the expected time when setting tstart to a number which is not a multiple of `dt-out` (or a number that doesn't fit restart_time + n * `dt-out`). E.g. setting tstart = 0.015 and dt-out=0.01. I've edited `call_plugin_dt` to now …
=> Outputting tavg files at expected times when restarting

pyfr/backends/base/backend.py, pyfr/backends/cuda/cublaslt.py, pyfr/backends/cuda/gimmik.py, pyfr/backends/hip/gimmik.py, pyfr/backends/hip/rocblas.py, pyfr/backends/metal/gimmik.py, pyfr/backends/opencl/gimmik.py
This requires each kernel to be appreciably faster than the current best in order to usurp it.  This should make the code easier to profile and also improve reproducibility.
The factor of 0.95 seems about right, but we may need to make it 0.9 (so a new kernel has to perform 10% better than the current best).
=> Improve reproducibility of kernel selection.

pyfr/plugins/tavg.py, pyfr/writers/native.py
The time average plugin was getting the output data precision from its own section in the ini file rather than the backend section. This could cause a mismatch in precision when passing data to the writer (e.g. simulation run in double precision but tavg done in single precision) which would cause half the domain to be zeroed out and the other half to have invalid data.
=> Time averaging bug fix

pyfr/plugins/base.py, pyfr/plugins/dtstats.py, pyfr/plugins/fluidforce.py, pyfr/plugins/fwh.py, pyfr/plugins/integrate.py, pyfr/plugins/pseudostats.py, pyfr/plugins/residual.py, pyfr/plugins/sampler.py, pyfr/writers/csv.py
This adds a `CSVWrapper` class (happy to rename if there is a better suggestion) to pyfr.writers.csv that handles some of what is in `init_csv` and also flushing to file. `init_csv` in pyfr.plugins.base now creates and returns a `CSVWrapper` class.
Let me know if there was a better way to do this or if I should also pull the `DatasetAppender` class outside of pyfr.plugins.base (I don't have any plans to use it in the mass flow controller BC, I just wasn't sure if it should live in the same place as `CSVWrapper`).
=> Refactoring CSV writing into a class

doc/src/installation.rst, pyfr/backends/hip/blasext.py, pyfr/backends/hip/driver.py, pyfr/backends/hip/gimmik.py, pyfr/backends/hip/packing.py, pyfr/backends/hip/provider.py, pyfr/backends/hip/rocblas.py, pyfr/backends/hip/types.py
This PR adds full support for HIP graphs, bringing the HIP backend on par with the CUDA backend.  However, whereas for simple test cases overhead decreased by a factor of ~2 when moving to graphs, for HIP overhead increases by ~2.  The performance impact for non-trivial cases still needs to be assessed, however.
=> HIP Graph Support
